# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connect_with_twitch',
            field=models.BooleanField(default=False),
        ),
    ]
