# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_connect_with_twitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
